site_name: pmpaulino-docs
repo_url: https://github.com/pmpaulino/docs

plugins:
  - search
  - multirepo:
      nav_repos:
        - name: timestamp
          import_url: 'https://github.com/pmpaulino/timestamp?branch=main'
          imports: [docs/index.md]
nav:
  - Home: index.md
  - Timestamp: timestamp/docs/index.md
