site_name: pmpaulino-docs
repo_url: https://github.com/pmpaulino/docs

plugins:
  - search
  - multirepo:
      cleanup: false
      keep_docs_dir: true
      nav_repos:
        - name: timestamp
          import_url: 'https://github.com/pmpaulino/timestamp?branch=main'
          imports: [docs/**]
nav:
  - Home: index.md
  - Timestamp: timestamp/docs/
