site_name: pmpaulino-docs
repo_url: https://github.com/pmpaulino/docs

plugins:
  - search
  - multirepo:
      cleanup: false
      keep_docs_dir: true
nav:
  - Docs: index.md
  - Timestamp: '!import https://github.com/pmpaulino/timestamp?branch=main&multi_docs=True&keep_docs_dir=True'

